# Generated by Django 6.0 on 2025-12-04 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fakultas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Fakultas",
            },
        ),
        migrations.CreateModel(
            name="Prodi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                (
                    "fakultas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prodi",
                        to="alumni.fakultas",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prodi",
            },
        ),
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nim", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("tahun_lulus", models.IntegerField()),
                ("status_bekerja", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fakultas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="alumni.fakultas",
                    ),
                ),
                (
                    "prodi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="alumni.prodi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alumni",
            },
        ),
    ]
