# Generated by Django 6.0 on 2025-12-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mata_kuliah",
                    models.CharField(
                        max_length=200, verbose_name="Subjek / Mata Kuliah"
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("Akademik", "Akademik & Kurikulum"),
                            ("Fasilitas", "Fasilitas & Sarana"),
                            ("Pelayanan", "Pelayanan Dosen/Staff"),
                            ("Lainnya", "Lainnya"),
                        ],
                        default="Akademik",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(default=5, verbose_name="Rating Kepuasan"),
                ),
                ("saran", models.TextField(verbose_name="Detail Masukan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Review"),
                            ("process", "Sedang Diproses"),
                            ("done", "Selesai / Ditindaklanjuti"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, verbose_name="Kirim sebagai Anonim"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="alumni.alumni",
                    ),
                ),
            ],
        ),
    ]
