# Generated by Django 6.0 on 2025-12-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mata_kuliah",
                    models.CharField(
                        help_text="Nama Mata Kuliah yang relevan/kurang relevan",
                        max_length=200,
                    ),
                ),
                (
                    "kesesuaian",
                    models.CharField(
                        choices=[
                            ("Sangat Baik", "Sangat Baik"),
                            ("Baik", "Baik"),
                            ("Cukup", "Cukup"),
                            ("Kurang", "Kurang"),
                        ],
                        max_length=20,
                    ),
                ),
                ("saran", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="alumni.alumni",
                    ),
                ),
            ],
        ),
    ]
