# Generated by Django 6.0 on 2025-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="kesesuaian",
            field=models.CharField(
                choices=[
                    ("Sangat Sesuai", "Sangat Sesuai"),
                    ("Sesuai", "Sesuai"),
                    ("Kurang", "Kurang"),
                    ("Tidak Sesuai", "Tidak Sesuai"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mata_kuliah",
            field=models.CharField(max_length=200, verbose_name="Nama Mata Kuliah"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="saran",
            field=models.TextField(verbose_name="Saran Perbaikan"),
        ),
    ]
