# Generated by Django 5.2.8 on 2025-11-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_pekerjaan",
                    models.CharField(
                        choices=[
                            ("Bekerja", "Bekerja"),
                            ("Wirausaha", "Wirausaha"),
                            ("Belum Bekerja", "Belum Bekerja"),
                            ("Studi Lanjut", "Studi Lanjut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("waktu_tunggu", models.IntegerField(blank=True, null=True)),
                (
                    "jenis_perusahaan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Swasta", "Swasta"),
                            ("Negeri", "Negeri / BUMN"),
                            ("StartUp", "StartUp"),
                            ("UMKM", "UMKM"),
                            ("Multinasional", "Multinasional"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "posisi_pekerjaan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Staff", "Staff"),
                            ("Supervisor", "Supervisor"),
                            ("Manager", "Manager"),
                            ("Direktur", "Direktur"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("gaji", models.IntegerField(blank=True, null=True)),
                (
                    "kesesuaian_jurusan",
                    models.CharField(
                        choices=[
                            ("Sangat Sesuai", "Sangat Sesuai"),
                            ("Sesuai", "Sesuai"),
                            ("Cukup", "Cukup"),
                            ("Kurang", "Kurang"),
                            ("Tidak Sesuai", "Tidak Sesuai"),
                        ],
                        max_length=20,
                    ),
                ),
                ("catatan", models.TextField(blank=True, null=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumni.alumni"
                    ),
                ),
            ],
        ),
    ]
