# Generated by Django 5.2.8 on 2025-11-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nim", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(max_length=100)),
                ("prodi", models.CharField(max_length=100)),
                ("tahun_lulus", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Bekerja", "Bekerja"),
                            ("Belum Bekerja", "Belum Bekerja"),
                            ("Wirausaha", "Wirausaha"),
                            ("Studi Lanjut", "Studi Lanjut"),
                        ],
                        default="Belum Bekerja",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
