# Generated by Django 6.0 on 2025-12-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perusahaan", models.CharField(max_length=200)),
                ("tahun_masuk", models.IntegerField()),
                ("bidang_pekerjaan", models.CharField(max_length=200)),
                (
                    "kesesuaian",
                    models.CharField(
                        choices=[
                            ("Sangat Sesuai", "Sangat Sesuai"),
                            ("Sesuai", "Sesuai"),
                            ("Kurang", "Kurang"),
                            ("Tidak Sesuai", "Tidak Sesuai"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gaji",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="alumni.alumni",
                    ),
                ),
            ],
        ),
    ]
