# Generated by Django 5.2.8 on 2025-11-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_kurikulum",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Sangat Buruk"),
                            (2, "2 - Buruk"),
                            (3, "3 - Cukup"),
                            (4, "4 - Baik"),
                            (5, "5 - Sangat Baik"),
                        ]
                    ),
                ),
                (
                    "rating_pengajar",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Sangat Buruk"),
                            (2, "2 - Buruk"),
                            (3, "3 - Cukup"),
                            (4, "4 - Baik"),
                            (5, "5 - Sangat Baik"),
                        ]
                    ),
                ),
                (
                    "rating_relevansi",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Sangat Buruk"),
                            (2, "2 - Buruk"),
                            (3, "3 - Cukup"),
                            (4, "4 - Baik"),
                            (5, "5 - Sangat Baik"),
                        ]
                    ),
                ),
                ("komentar", models.TextField()),
                ("saran", models.TextField(blank=True, null=True)),
                ("tanggal_input", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumni.alumni"
                    ),
                ),
            ],
        ),
    ]
